// 调色板目录:token 清单、DSH 默认外观、内置主题(含默认主题卡片)
import { createManagedColors } from './color-utils.js'
import { chatTokens } from './chat.js'
/** 核心 token 子集(旧版升级兼容:仅校验这些,缺失的品牌 token 用默认值补齐)。 */
export const BASE_TOKEN_NAMES = [
      '--dsw-alias-bg-base', '--dsw-alias-bg-layer-1', '--dsw-alias-bg-layer-2', '--dsw-alias-bg-overlay',
      '--dsw-alias-border-l1', '--dsw-alias-border-l2', '--dsw-alias-brand-primary',
      '--dsw-alias-label-primary', '--dsw-alias-label-secondary',
      '--dsw-alias-state-error-primary', '--dsw-alias-state-warn-primary', '--dsw-alias-state-success-primary',
      '--dsw-specific-sidebar-fill',
      '--dsw-alias-button-info-fill', '--dsw-alias-button-info-hover',
      '--dsw-alias-state-business-primary', '--dsw-alias-state-business-tertiary',
      '--dsw-specific-sidebar-nav-item-active', '--dsw-specific-sidebar-nav-item-active-accent',
      '--dsw-static-deepseek-500', '--dsw-static-deepseek-200', '--dsw-static-deepseek-450',
      '--dsw-specific-bubble', '--dsw-specific-bubble-highlight',
    ]

    /** 扩展 token 集(DSH 设计平台剩余别名/专用 token 与品牌静态色):表面层级、文字层级、
     * 交互反馈、Markdown、状态补充、滚动条、浮层等。生成器派生或按 DSH 默认值兜底。 */

export const EXTENDED_TOKEN_NAMES = [
      // 表面层级
      '--dsw-alias-bg-layer-3', '--dsw-alias-bg-module-platform', '--dsw-alias-bg-multi-select', '--dsw-alias-bg-skeleton',
      '--dsw-alias-bg-mask-1', '--dsw-alias-bg-mask-2', '--dsw-alias-bg-mask-3', '--dsw-alias-bg-mask-drop', '--dsw-alias-bg-mask-photo',
      // 边框
      '--dsw-alias-border-l3', '--dsw-alias-border-l4', '--dsw-alias-border-l2-darkmode-thin',
      '--dsw-alias-border-inverted', '--dsw-alias-border-inverted2',
      // 品牌
      '--dsw-alias-brand-text', '--dsw-alias-brand-primary-invert', '--dsw-alias-brand-primary-new-colorprimary-new-color',
      // 按钮
      '--dsw-alias-button-primary-fill', '--dsw-alias-button-primary-hover', '--dsw-alias-button-primary-dimmed',
      '--dsw-alias-button-contrast-fill', '--dsw-alias-button-elevated-fill',
      '--dsw-alias-button-floating-fill', '--dsw-alias-button-floating-hover',
      '--dsw-alias-button-ghost-active-fill', '--dsw-alias-button-ghost-active-border', '--dsw-alias-button-ghost-active-hover',
      '--dsw-alias-button-tool-bar-fill', '--dsw-alias-button-tool-bar-fill-invisible', '--dsw-alias-button-tool-bar-hover',
      // 交互反馈
      '--dsw-alias-interactive-bg-hover', '--dsw-alias-interactive-bg-active', '--dsw-alias-interactive-bg-hover-accent',
      '--dsw-alias-interactive-bg-hover-danger', '--dsw-alias-interactive-bg-hover-solid',
      // 文字层级
      '--dsw-alias-label-tertiary', '--dsw-alias-label-caption', '--dsw-alias-label-dimmed',
      '--dsw-alias-label-primary-dimmed', '--dsw-alias-label-primary-foreground', '--dsw-alias-label-primary-inverted', '--dsw-alias-label-primary-bluish',
      // Markdown
      '--dsw-alias-markdown-code-block', '--dsw-alias-markdown-code-block-banner', '--dsw-alias-markdown-inline-code',
      '--dsw-alias-markdown-citation', '--dsw-alias-markdown-placeholder', '--dsw-alias-markdown-tag',
      '--dsw-alias-markdown-code-segment-selected', '--dsw-alias-markdown-code-segment-unselected',
      // 滚动条
      '--dsw-alias-scrollbar-bg-l1', '--dsw-alias-scrollbar-bg-l2', '--dsw-alias-scrollbar-hover-l1', '--dsw-alias-scrollbar-hover-l2',
      // 状态补充
      '--dsw-alias-state-error-secondary', '--dsw-alias-state-warn-label', '--dsw-alias-state-warn-secondary', '--dsw-alias-state-warn-tertiary',
      '--dsw-alias-state-success-secondary', '--dsw-alias-state-success-tertiary',
      // 浮层
      '--dsw-alias-toast-bg', '--dsw-alias-tooltip-bg',
      // 专用
      '--dsw-specific-menu', '--dsw-specific-selector', '--dsw-specific-input-major', '--dsw-specific-login-input',
      '--dsw-specific-tip', '--dsw-specific-sidebar-nav-item-hover',
      // 品牌静态色(被组件直接消费:meter 色调、轨迹强调色)
      '--dsw-static-blue-400', '--dsw-static-blue-450', '--dsw-static-blue-500',
    ]

    /** 完整覆盖清单:核心 + 扩展,供覆盖层应用与持久化补齐。 */

export const TOKEN_NAMES = [...BASE_TOKEN_NAMES, ...EXTENDED_TOKEN_NAMES]

    /** 旧版主题库中的核心 token 子集(升级兼容:仅校验这些,缺失的品牌 token 用默认值补齐)。 */

export const CORE_TOKEN_NAMES = [
      '--dsw-alias-bg-base', '--dsw-alias-bg-layer-1', '--dsw-alias-bg-layer-2', '--dsw-alias-bg-overlay',
      '--dsw-alias-border-l1', '--dsw-alias-border-l2', '--dsw-alias-brand-primary',
      '--dsw-alias-label-primary', '--dsw-alias-label-secondary',
      '--dsw-alias-state-error-primary', '--dsw-alias-state-warn-primary', '--dsw-alias-state-success-primary',
      '--dsw-specific-sidebar-fill',
    ]

    /** DSH 内置外观的 token 默认值(明暗混合缺半与旧库补齐时的兜底)。 */

export const DEFAULT_PALETTE = {
      light: {
        '--dsw-alias-bg-base': '#ffffff',
        '--dsw-alias-bg-layer-1': '#ffffff',
        '--dsw-alias-bg-layer-2': '#ffffff',
        '--dsw-alias-bg-overlay': '#e9ecf2',
        '--dsw-alias-border-l1': 'rgba(0, 0, 0, 0.04)',
        '--dsw-alias-border-l2': 'rgba(0, 0, 0, 0.10)',
        '--dsw-alias-brand-primary': '#0f1115',
        '--dsw-alias-label-primary': '#0f1115',
        '--dsw-alias-label-secondary': '#61666b',
        '--dsw-alias-state-error-primary': '#ec1313',
        '--dsw-alias-state-warn-primary': '#f59e0b',
        '--dsw-alias-state-success-primary': '#22c55e',
        '--dsw-specific-sidebar-fill': '#f9fafb',
        '--dsw-alias-button-info-fill': '#4176e6',
        '--dsw-alias-button-info-hover': '#679efe',
        '--dsw-alias-state-business-primary': '#4176e6',
        '--dsw-alias-state-business-tertiary': '#e4edfd',
        '--dsw-specific-sidebar-nav-item-active': '#ebedf2',
        '--dsw-specific-sidebar-nav-item-active-accent': '#e4edfd',
        '--dsw-static-deepseek-500': '#4176e6',
        '--dsw-static-deepseek-200': '#d3e2ff',
        '--dsw-static-deepseek-450': '#5686fe',
        '--dsw-specific-bubble': '#edf3fe',
        '--dsw-specific-bubble-highlight': '#d3e2ff',
        '--dsw-alias-bg-layer-3': '#ffffff',
        '--dsw-alias-bg-module-platform': '#f5f6f7',
        '--dsw-alias-bg-multi-select': '#f5f6f7',
        '--dsw-alias-bg-skeleton': 'rgba(0, 0, 0, 0.04)',
        '--dsw-alias-bg-mask-1': 'rgba(0, 0, 0, 0.24)',
        '--dsw-alias-bg-mask-2': 'rgba(0, 0, 0, 0.12)',
        '--dsw-alias-bg-mask-3': 'rgba(0, 0, 0, 0.48)',
        '--dsw-alias-bg-mask-drop': 'rgba(255, 255, 255, 0.7)',
        '--dsw-alias-bg-mask-photo': 'rgba(0, 0, 0, 0.88)',
        '--dsw-alias-border-l3': 'rgba(0, 0, 0, 0.12)',
        '--dsw-alias-border-l4': 'rgba(0, 0, 0, 0.16)',
        '--dsw-alias-border-l2-darkmode-thin': 'rgba(0, 0, 0, 0.1)',
        '--dsw-alias-border-inverted': 'rgba(0, 0, 0, 0)',
        '--dsw-alias-border-inverted2': 'rgba(0, 0, 0, 0)',
        '--dsw-alias-brand-text': '#0f1115',
        '--dsw-alias-brand-primary-invert': '#0f1115',
        '--dsw-alias-brand-primary-new-colorprimary-new-color': '#4176e6',
        '--dsw-alias-button-primary-fill': '#0f1115',
        '--dsw-alias-button-primary-hover': '#43454a',
        '--dsw-alias-button-primary-dimmed': '#ebeef2',
        '--dsw-alias-button-contrast-fill': '#61666b',
        '--dsw-alias-button-elevated-fill': '#ffffff',
        '--dsw-alias-button-floating-fill': '#ffffff',
        '--dsw-alias-button-floating-hover': '#f1f3f5',
        '--dsw-alias-button-ghost-active-fill': '#ebeef2',
        '--dsw-alias-button-ghost-active-border': '#979da6',
        '--dsw-alias-button-ghost-active-hover': '#e9ecf2',
        '--dsw-alias-button-tool-bar-fill': 'rgba(84, 85, 87, 0.5)',
        '--dsw-alias-button-tool-bar-fill-invisible': 'rgba(31, 31, 31, 0.36)',
        '--dsw-alias-button-tool-bar-hover': 'rgba(84, 85, 87, 0.6)',
        '--dsw-alias-interactive-bg-hover': 'rgba(38, 49, 72, 0.06)',
        '--dsw-alias-interactive-bg-active': 'rgba(38, 49, 72, 0.1)',
        '--dsw-alias-interactive-bg-hover-accent': 'rgba(38, 49, 72, 0.14)',
        '--dsw-alias-interactive-bg-hover-danger': 'rgba(236, 19, 19, 0.05)',
        '--dsw-alias-interactive-bg-hover-solid': '#f1f3f5',
        '--dsw-alias-label-tertiary': '#81858c',
        '--dsw-alias-label-caption': '#adb2b8',
        '--dsw-alias-label-dimmed': '#e1e5ee',
        '--dsw-alias-label-primary-dimmed': '#151517',
        '--dsw-alias-label-primary-foreground': '#ffffff',
        '--dsw-alias-label-primary-inverted': '#ffffff',
        '--dsw-alias-label-primary-bluish': '#0e3074',
        '--dsw-alias-markdown-code-block': '#f9fafb',
        '--dsw-alias-markdown-code-block-banner': '#f9fafb',
        '--dsw-alias-markdown-inline-code': '#ebeef2',
        '--dsw-alias-markdown-citation': '#ebeef2',
        '--dsw-alias-markdown-placeholder': '#f5f6f7',
        '--dsw-alias-markdown-tag': '#f1f3f5',
        '--dsw-alias-markdown-code-segment-selected': '#ffffff',
        '--dsw-alias-markdown-code-segment-unselected': '#f1f3f5',
        '--dsw-alias-scrollbar-bg-l1': '#e5e5e5',
        '--dsw-alias-scrollbar-bg-l2': '#e5e5e5',
        '--dsw-alias-scrollbar-hover-l1': '#d4d4d4',
        '--dsw-alias-scrollbar-hover-l2': '#d4d4d4',
        '--dsw-alias-state-error-secondary': '#f25a5a',
        '--dsw-alias-state-warn-label': '#dd8629',
        '--dsw-alias-state-warn-secondary': '#f7ad31',
        '--dsw-alias-state-warn-tertiary': '#fef5e7',
        '--dsw-alias-state-success-secondary': '#4ed17e',
        '--dsw-alias-state-success-tertiary': '#e6faed',
        '--dsw-alias-toast-bg': '#353638',
        '--dsw-alias-tooltip-bg': '#2c2c2e',
        '--dsw-specific-menu': '#ffffff',
        '--dsw-specific-selector': '#f5f6f7',
        '--dsw-specific-input-major': '#ffffff',
        '--dsw-specific-login-input': '#f9fafb',
        '--dsw-specific-tip': '#f5f6f7',
        '--dsw-specific-sidebar-nav-item-hover': '#f1f3f5',
        '--dsw-static-blue-400': '#60a5fa',
        '--dsw-static-blue-450': '#4d93f8',
        '--dsw-static-blue-500': '#3b82f6',
      },
      dark: {
        '--dsw-alias-bg-base': '#151517',
        '--dsw-alias-bg-layer-1': '#232324',
        '--dsw-alias-bg-layer-2': '#2c2c2e',
        '--dsw-alias-bg-overlay': '#61666b',
        '--dsw-alias-border-l1': 'rgba(255, 255, 255, 0.06)',
        '--dsw-alias-border-l2': 'rgba(255, 255, 255, 0.12)',
        '--dsw-alias-brand-primary': '#f9fafb',
        '--dsw-alias-label-primary': '#f9fafb',
        '--dsw-alias-label-secondary': '#cfd3d6',
        '--dsw-alias-state-error-primary': '#f25a5a',
        '--dsw-alias-state-warn-primary': '#f59e0b',
        '--dsw-alias-state-success-primary': '#22c55e',
        '--dsw-specific-sidebar-fill': '#1b1b1c',
        '--dsw-alias-button-info-fill': '#679efe',
        '--dsw-alias-button-info-hover': '#4176e6',
        '--dsw-alias-state-business-primary': '#679efe',
        '--dsw-alias-state-business-tertiary': '#34415b',
        '--dsw-specific-sidebar-nav-item-active': '#43454a',
        '--dsw-specific-sidebar-nav-item-active-accent': '#353536',
        '--dsw-static-deepseek-500': '#4176e6',
        '--dsw-static-deepseek-200': '#d3e2ff',
        '--dsw-static-deepseek-450': '#5686fe',
        '--dsw-specific-bubble': '#2c2c2e',
        '--dsw-specific-bubble-highlight': '#43454a',
        '--dsw-alias-bg-layer-3': '#353638',
        '--dsw-alias-bg-module-platform': '#353638',
        '--dsw-alias-bg-multi-select': '#212123',
        '--dsw-alias-bg-skeleton': 'rgba(255, 255, 255, 0.08)',
        '--dsw-alias-bg-mask-1': 'rgba(0, 0, 0, 0.5)',
        '--dsw-alias-bg-mask-2': 'rgba(0, 0, 0, 0.2)',
        '--dsw-alias-bg-mask-3': 'rgba(0, 0, 0, 0.48)',
        '--dsw-alias-bg-mask-drop': 'rgba(39, 39, 48, 0.7)',
        '--dsw-alias-bg-mask-photo': 'rgba(0, 0, 0, 0.88)',
        '--dsw-alias-border-l3': 'rgba(255, 255, 255, 0.16)',
        '--dsw-alias-border-l4': 'rgba(255, 255, 255, 0.2)',
        '--dsw-alias-border-l2-darkmode-thin': 'rgba(255, 255, 255, 0.06)',
        '--dsw-alias-border-inverted': 'rgba(255, 255, 255, 0.06)',
        '--dsw-alias-border-inverted2': 'rgba(255, 255, 255, 0.08)',
        '--dsw-alias-brand-text': '#f9fafb',
        '--dsw-alias-brand-primary-invert': '#f9fafb',
        '--dsw-alias-brand-primary-new-colorprimary-new-color': '#5686fe',
        '--dsw-alias-button-primary-fill': '#f9fafb',
        '--dsw-alias-button-primary-hover': '#ebeef2',
        '--dsw-alias-button-primary-dimmed': '#43454a',
        '--dsw-alias-button-contrast-fill': '#f9fafb',
        '--dsw-alias-button-elevated-fill': '#43454a',
        '--dsw-alias-button-floating-fill': '#2c2c2e',
        '--dsw-alias-button-floating-hover': '#353638',
        '--dsw-alias-button-ghost-active-fill': '#43454a',
        '--dsw-alias-button-ghost-active-border': '#81858c',
        '--dsw-alias-button-ghost-active-hover': '#61666b',
        '--dsw-alias-button-tool-bar-fill': 'rgba(84, 85, 87, 0.5)',
        '--dsw-alias-button-tool-bar-fill-invisible': 'rgba(31, 31, 31, 0.36)',
        '--dsw-alias-button-tool-bar-hover': 'rgba(84, 85, 87, 0.6)',
        '--dsw-alias-interactive-bg-hover': 'rgba(255, 255, 255, 0.08)',
        '--dsw-alias-interactive-bg-active': 'rgba(255, 255, 255, 0.14)',
        '--dsw-alias-interactive-bg-hover-accent': 'rgba(255, 255, 255, 0.24)',
        '--dsw-alias-interactive-bg-hover-danger': 'rgba(242, 90, 90, 0.15)',
        '--dsw-alias-interactive-bg-hover-solid': '#353638',
        '--dsw-alias-label-tertiary': '#adb2b8',
        '--dsw-alias-label-caption': '#81858c',
        '--dsw-alias-label-dimmed': '#43454a',
        '--dsw-alias-label-primary-dimmed': '#ebeef2',
        '--dsw-alias-label-primary-foreground': '#0f1115',
        '--dsw-alias-label-primary-inverted': '#353638',
        '--dsw-alias-label-primary-bluish': '#f9fafb',
        '--dsw-alias-markdown-code-block': '#1b1b1c',
        '--dsw-alias-markdown-code-block-banner': '#2c2c2e',
        '--dsw-alias-markdown-inline-code': '#2c2c2e',
        '--dsw-alias-markdown-citation': '#353638',
        '--dsw-alias-markdown-placeholder': '#2c2c2e',
        '--dsw-alias-markdown-tag': '#2c2c2e',
        '--dsw-alias-markdown-code-segment-selected': '#353638',
        '--dsw-alias-markdown-code-segment-unselected': '#1b1b1c',
        '--dsw-alias-scrollbar-bg-l1': '#3c3c3d',
        '--dsw-alias-scrollbar-bg-l2': '#545557',
        '--dsw-alias-scrollbar-hover-l1': '#545557',
        '--dsw-alias-scrollbar-hover-l2': '#65676b',
        '--dsw-alias-state-error-secondary': '#f25a5a',
        '--dsw-alias-state-warn-label': '#dd8629',
        '--dsw-alias-state-warn-secondary': '#f7ad31',
        '--dsw-alias-state-warn-tertiary': '#27241f',
        '--dsw-alias-state-success-secondary': '#4ed17e',
        '--dsw-alias-state-success-tertiary': '#233c2c',
        '--dsw-alias-toast-bg': '#43454a',
        '--dsw-alias-tooltip-bg': '#43454a',
        '--dsw-specific-menu': '#353638',
        '--dsw-specific-selector': '#353638',
        '--dsw-specific-input-major': '#2c2c2e',
        '--dsw-specific-login-input': '#1b1b1c',
        '--dsw-specific-tip': '#353638',
        '--dsw-specific-sidebar-nav-item-hover': '#2c2c2e',
        '--dsw-static-blue-400': '#60a5fa',
        '--dsw-static-blue-450': '#4d93f8',
        '--dsw-static-blue-500': '#3b82f6',
      },
    }

    /** 内置主题统一为带明/暗变体槽的结构(与导入主题一致)。 */

export const withVariants = (p) => ({
      ...p,
      lightVariants: [{ label: '浅色', tokens: p.light }],
      darkVariants: [{ label: '深色', tokens: p.dark }],
    })

    /** 默认主题 = DSH 原生外观(恢复默认即应用此卡片)。 */

export const DEFAULT_THEME = withVariants({ id: 'dsh-default', label: 'DSH 默认', light: DEFAULT_PALETTE.light, dark: DEFAULT_PALETTE.dark })


export const PALETTES = [
      DEFAULT_THEME,
      withVariants({ id: 'dsh-chat', label: 't3 chat', light: chatTokens('light'), dark: chatTokens('dark') }),
      withVariants({ id: 'grove', label: 'Grove', light: createManagedColors('light', '#f2f8f4', '#19734a'), dark: createManagedColors('dark', '#1d2b24', '#69d69a') }),
      withVariants({ id: 'ocean', label: 'Ocean', light: createManagedColors('light', '#f2f7fb', '#2878b8'), dark: createManagedColors('dark', '#1b2938', '#70b9ee') }),
      withVariants({ id: 'ember', label: 'Ember', light: createManagedColors('light', '#fff6ef', '#c4602f'), dark: createManagedColors('dark', '#30231e', '#f39a62') }),
      withVariants({ id: 'iris', label: 'Iris', light: createManagedColors('light', '#f7f4fc', '#7254b9'), dark: createManagedColors('dark', '#29243b', '#ad92f5') }),
    ]

    // ---- 调色板覆盖层状态 ----


